; PlatformIO Project Configuration
; Target: Waveshare ESP32-S3-Touch-LCD-7 (1024x600)

[env:waveshare_esp32s3_7]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Flash / RAM
board_build.arduino.memory_type = qio_opi
board_upload.flash_size         = 16MB
board_build.flash_mode          = qio
board_build.partitions          = huge_app.csv

; Speed
monitor_speed = 115200
upload_speed  = 921600

; USB CDC for serial over native USB port
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLV_CONF_INCLUDE_SIMPLE
  -I include
  -I src

lib_deps =
  lvgl/lvgl @ ^8.3.11
  lovyan03/LovyanGFX @ ^1.1.16
